### ISSUE TITLE
3-24 Portfolio Flexbox exercise - Gill Guimaraes

### ISSUE THREAD

**Issue by TechNestOwl** [wsvoboda/digitalcrafts-03-2021#1]
https://github.com/TechNestOwl/digital_crafts/blob/main/week3/day3/portfolio.html 
https://github.com/TechNestOwl/digital_crafts/blob/main/week3/day3/portfolio.css
https://github.com/TechNestOwl/digital_crafts/tree/main/week3/day3/assests

I wasn't sure if you wanted us to make an actual portfolio, or just a simple about me site to demonstrate understanding of Flexbox...
 
-completed

**Comment by wsvoboda** [comment]
You put this under my repo instead of the class's!
