### ISSUE TITLE
05/11_Tatien_Miller_GarageHw

### ISSUE THREAD

**Issue by tatmil-99** [wsvoboda/digitalcrafts-03-2021#2]
https://github.com/tatmil-99/digitalcrafts-03-2021/tree/main/week10/day2/homework/car-garage
Not really sure what i'm doing. I made something show up on a page, but wasn't sure how to include all the components.

**Comment by wsvoboda** [comment]
Hi Tate! You accidentally opened this on my page instead of the DC page :)
